image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_USER:  $DOCKER_USER
  DOCKER_PASSWORD:  $DOCKER_PASSWORD

services:
- docker:dind

before_script:
- docker info

stages:
  - build
  - test
  - deploy

build-frontend:
  stage: build
  script:
    - echo "Checking the frontend build"
    - docker build -t frontend -f ./frontend/Dockerfile ./frontend/ 
  after_script:
    - echo "Success building"

build-backend:
  stage: build
  script:
    - echo "Checking the backend build"
    - docker build -t backend -f ./backend/Dockerfile ./backend/
  after_script:
    - echo "Success building"

test-front:
  image: docker/compose:latest
  stage: test
  script:
    - echo "Checking the frontend tests"
    - docker-compose run --entrypoint "npm run coverage" frontend
  after_script:
    - echo "Success testing"
    
test-back:
  image: docker/compose:latest
  stage: test
  script:
    - echo "Checking the backend tests"
    - docker-compose run --entrypoint "npm run unittest" backend
  after_script:
    - echo "Success testing"

deploy:
  stage: deploy  
  before_script:
    - echo "Log in DockerHub"
    - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin


  script:
    - echo "Deploying on hub..."
    - docker build -t $DOCKER_USER/workshop-ci-entrega_02:backend -f ./backend/Dockerfile ./backend/ 
    - docker build -t $DOCKER_USER/workshop-ci-entrega_02:frontend -f ./backend/Dockerfile ./frontend/ 
    - docker push DOCKER_USER/workshop-ci-entrega_02:frontend
    - docker push DOCKER_USER/workshop-ci-entrega_02:backend
    - echo "Sucess deploying to hub"
