image: docker:stable

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_USER:  $DOCKER_USER
  DOCKER_PASSWORD:  $DOCKER_PASSWORD

services:
- docker:dind

before_script:
- docker info

stages:
  - build
  - test
  - deploy

build-frontend:
  stage: build
  script:
    - echo "Checking the frontend build"
    - docker build -t frontend -f ./frontend/Dockerfile ./frontend/ 
  after_script:
    - echo "Success building"

build-backend:
  stage: build
  script:
    - echo "Checking the backend build"
    - docker build -t backend -f ./backend/Dockerfile ./backend/
  after_script:
    - echo "Success building"

test-front:
  image: docker/compose:latest
  stage: test
  script:
    - echo "Checking the frontend tests"
    - docker-compose run --entrypoint "npm run coverage" frontend
  after_script:
    - echo "Success testing"
    
test-back:
  image: docker/compose:latest
  stage: test
  script:
    - echo "Checking the backend tests"
    - docker-compose run --entrypoint "npm run unittest" backend
  after_script:
    - echo "Success testing"

deploy-app:
  stage: deploy  
  before_script:
    - echo "Log in DockerHub"
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"


  script:
    - echo "Deploying on hub..."
    - docker build -f ./backend/Dockerfile -t $DOCKER_USER/workshop-ci-entrega_02_backend:backend ./backend
    - docker build -f ./frontend/Dockerfile -t $DOCKER_USER/workshop-ci-entrega-02_frontend:frontend ./frontend
    - docker push $DOCKER_USER/workshop-ci-entrega-02_frontend:frontend
    - docker push $DOCKER_USER/workshop-ci-entrega-02_backend:backend
    - echo "Sucess deploying to hub"
